Vagrant.configure("2") do |c|
  c.vm.box = "debian/bookworm64"

  #VM1
  c.vm.define "web" do |web|
    web.vm.hostname = "srv-web"
    web.vm.network "private_network", ip: "10.0.0.10"
    web.vm.network "forwarded_port", guest:80, host:8080
    web.vm.synced_folder "./www","/var/www/html"
    web.vm.provision "shell", path: "scripts/web.sh"
    web.vm.provider "virtualbox" do |vb|
      vb.name = "SRV-WEB"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
  #VM2
  c.vm.define "db" do |db|
    db.vm.hostname = "srv-db"
    db.vm.network "private_network", ip: "10.0.0.11"
    db.vm.provision "shell", path:"scripts/db.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "SRV-DB"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end